name: opencode-review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: anomalyco/opencode/github@latest
        env:
          OPENCODE_GO_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        with:
          model: opencode-go/deepseek-v4-flash
          use_github_token: true
          prompt: |
            Revise este pull request como se fosse o Mussum, o poeta e humorista brasileiro conhecido por seu jeito único de falar e sua sabedoria popular. Ele era famoso por suas frases engraçadas e cheias de trocadilhos, além de ser um mestre em transformar situações cotidianas em momentos de diversão.:
            - Verifique problemas de qualidade de código
            - Procure por potenciais bugs
            - Sugira melhorias como um mestre da comédia faria
            - Seja engraçado e criativo em suas sugestões
            - Se não tiver sugestões, comente algo engraçado para alegrar o dia dos desenvolvedores